name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Select test type. "basic" for fast checks, "full" for all, "tauri-only" for build tests.'
        required: true
        default: 'basic'
        type: choice
        options:
        - basic
        - full
        - tauri-only
      platforms:
        description: 'Select platforms to build (only for "full" or "tauri-only" types).'
        required: false
        type: choice
        default: 'all'
        options:
        - all
        - ubuntu
        - windows
        - macos
        - ubuntu-windows
        - ubuntu-macos
        - windows-macos
      upload_artifacts:
        description: 'Upload build artifacts (consumes storage space).'
        required: false
        type: boolean
        default: false

jobs:
  lint-and-build:
    if: github.event_name != 'workflow_dispatch' || (github.event.inputs.test_type == 'basic' || github.event.inputs.test_type == 'full')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run linting
        run: pnpm lint
      - name: Type check
        run: pnpm tsc --noEmit
      - name: Build
        run: pnpm build

  test-tauri-ubuntu:
    needs: lint-and-build
    if: >-
      github.event_name == 'workflow_dispatch' &&
      (github.event.inputs.test_type == 'tauri-only' || github.event.inputs.test_type == 'full') &&
      (github.event.inputs.platforms == 'all' || github.event.inputs.platforms == 'ubuntu' || github.event.inputs.platforms == 'ubuntu-windows' || github.event.inputs.platforms == 'ubuntu-macos')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Install Rust dependencies
        run: sudo apt-get update && sudo apt-get install -y libwebkit2gtk-4.0-dev build-essential curl wget file libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build Tauri app (Debug)
        run: pnpm tauri build --debug
      - name: Upload build artifacts (if requested)
        if: ${{ github.event.inputs.upload_artifacts }}
        uses: actions/upload-artifact@v4
        with:
          name: chatless-debug-ubuntu
          path: src-tauri/target/debug/bundle/
          retention-days: 7

  test-tauri-windows:
    needs: lint-and-build
    if: >-
      github.event_name == 'workflow_dispatch' &&
      (github.event.inputs.test_type == 'tauri-only' || github.event.inputs.test_type == 'full') &&
      (github.event.inputs.platforms == 'all' || github.event.inputs.platforms == 'windows' || github.event.inputs.platforms == 'ubuntu-windows' || github.event.inputs.platforms == 'windows-macos')
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build Tauri app (Debug)
        run: pnpm tauri build --debug
      - name: Upload build artifacts (if requested)
        if: ${{ github.event.inputs.upload_artifacts }}
        uses: actions/upload-artifact@v4
        with:
          name: chatless-debug-windows
          path: src-tauri/target/debug/bundle/
          retention-days: 7

  test-tauri-macos:
    needs: lint-and-build
    if: >-
      github.event_name == 'workflow_dispatch' &&
      (github.event.inputs.test_type == 'tauri-only' || github.event.inputs.test_type == 'full') &&
      (github.event.inputs.platforms == 'all' || github.event.inputs.platforms == 'macos' || github.event.inputs.platforms == 'ubuntu-macos' || github.event.inputs.platforms == 'windows-macos')
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build Tauri app (Debug)
        run: pnpm tauri build --debug
      - name: Upload build artifacts (if requested)
        if: ${{ github.event.inputs.upload_artifacts }}
        uses: actions/upload-artifact@v4
        with:
          name: chatless-debug-macos
          path: src-tauri/target/debug/bundle/
          retention-days: 7