name: CI

on:
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Select test type'
        required: true
        default: 'basic'
        type: choice
        options:
        - basic
        - full
        - tauri-only
      upload_artifacts:
        description: 'Upload build artifacts (consumes storage space)'
        required: false
        type: boolean
        default: false

jobs:
  test:
    if: ${{ github.event.inputs.test_type == 'basic' || github.event.inputs.test_type == 'full' }}
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'pnpm'
    
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: latest
    
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    
    - name: Run linting
      run: pnpm lint
    
    - name: Type check
      run: pnpm tsc --noEmit
    
    - name: Build
      run: pnpm build

  test-tauri:
    if: ${{ github.event.inputs.test_type == 'tauri-only' || github.event.inputs.test_type == 'full' }}
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'pnpm'
    
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: latest
    
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    
    - name: Install Tauri CLI
      run: pnpm tauri --version
    
    - name: Build Tauri app
      run: pnpm tauri build --debug
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Upload build artifacts (if requested)
      if: ${{ github.event.inputs.upload_artifacts }}
      uses: actions/upload-artifact@v4
      with:
        name: chatless-debug-${{ matrix.platform }}
        path: src-tauri/target/debug/bundle/
        retention-days: 7 